-- 1. Створення таблиці користувачів (users)
CREATE TABLE public.users (
  uid uuid not null primary key default uuid_generate_v4(),
  codename text not null,
  age integer default 18,
  bio text,
  interests text[],
  "avatarColor" text default 'bg-indigo-500',
  lat double precision,
  lng double precision,
  "isOnline" boolean default true,
  "createdAt" timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Створення таблиці чату (city_chat)
CREATE TABLE public.city_chat (
  id bigint generated by default as identity primary key,
  text text not null,
  "userId" uuid not null,
  codename text not null,
  "avatarColor" text,
  "createdAt" timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Дозволити всім читати і писати (Для простоти, вимикаємо або налаштовуємо RLS - Row Level Security)
-- Увага: для реального проекту краще налаштувати більш суворі правила (Policies).
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON public.users FOR UPDATE USING (true);

ALTER TABLE public.city_chat ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.city_chat FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON public.city_chat FOR INSERT WITH CHECK (true);

-- 4. Увімкнути Realtime для таблиць (щоб чат і карта оновлювались миттєво)
alter publication supabase_realtime add table public.users;
alter publication supabase_realtime add table public.city_chat;
