import { MapUser } from './types';

// Coordinates for Kobelyaky, Poltava Oblast, Ukraine
export const CITY_CENTER = [49.1444, 34.1969]; 

export const MOCK_USERS: MapUser[] = [
  {
    id: 'u1',
    codename: 'Лиса',
    age: 22,
    gender: 'female',
    bio: 'Люблю гулять возле Ворсклы и пить кофе. Ищу кого-то для вечерних прогулок.',
    interests: ['кофе', 'прогулки', 'музыка'],
    avatarColor: 'bg-rose-500',
    lat: 49.1460,
    lng: 34.1980,
    isOnline: true,
  },
  {
    id: 'u2',
    codename: 'Неизвестный',
    age: 25,
    gender: 'male',
    bio: 'Только вернулся в город, ищу компанию. Увлекаюсь машинами и видеоиграми.',
    interests: ['авто', 'игры', 'пиво'],
    avatarColor: 'bg-blue-500',
    lat: 49.1432,
    lng: 34.1950,
    isOnline: false,
  },
  {
    id: 'u3',
    codename: 'Сова',
    age: 20,
    gender: 'female',
    bio: 'Не сплю по ночам. Рисую, слушаю эмбиент. Хочу найти соулмейта.',
    interests: ['искусство', 'ночь', 'эмбиент'],
    avatarColor: 'bg-purple-500',
    lat: 49.1480,
    lng: 34.1920,
    isOnline: true,
  },
  {
    id: 'u4',
    codename: 'Волк',
    age: 28,
    gender: 'male',
    bio: 'Занимаюсь спортом, бегаю по утрам. Буду рад компании на пробежку.',
    interests: ['спорт', 'зож', 'бег'],
    avatarColor: 'bg-slate-700',
    lat: 49.1415,
    lng: 34.2001,
    isOnline: true,
  },
  {
    id: 'u5',
    codename: 'Кот',
    age: 24,
    gender: 'any',
    bio: 'Просто ищу интересное общение без лишних вопросов. Люблю мемы и кино.',
    interests: ['кино', 'общение', 'мемы'],
    avatarColor: 'bg-amber-500',
    lat: 49.1455,
    lng: 34.1900,
    isOnline: false,
  },
];
